print("\na/")
print(" Negation: Exist a person, he/ she is blond but he/ she is not westerners.")
print(" Contrapositive: For all people, if they are not westerners then they are not blond")
print(" Converse: For all people, if they are westerners then they are blond")
print(" Inverse: For all people, if they are not blond then they are not westerners")

print("\nb/")
print(" Negation: For all people, if their hair is black then they are not westerner")
print(" Contrapositive: Exist a person, whose is not a westerner but hair is not black")
print(" Converse: Exist a person, whose is a westerner but hair is black")
print(" Inverse: Exist a person, whose hair is not black but is not a westerner")

print("\nc/")
print(" Negation: Exist a student, he/ she studies correctly but he/ she has not high score")
print(" Contrapositive: For all students, if they have not high score then theys are not study correctly")
print(" Converse: For all students, if they have high score then they study correctly")
print(" Inverse: For all students, if they are not study correctly then they have not high score")

print("\nd/")
print(" Negation: Exist a mammal, it lives in the sea but it not either dolphin or whale")
print(" Contrapositive: For all mammal, if they are not dolphins or whales then they are not live in the sea")
print(" Converse: For all mammal, if they are either dophins or whales then they are live in the sea")
print(" Inverse: For all mammal, if they are not live in the sea then they are not either dophins or whales")

print("\ne/")
print(" Negation: Exist a bird, it doesn't have wings and can not swim but it is not penguin")
print(" Contrapositive: For all birds, if they are not penguins then they have wings and can not swim")
print(" Converse: For all birds, if they are penguins then they don't have wings and can swim")
print(" Inverse: For all birds, if they have wings and can not swim then they are not penguins")

print("\nf/")
print(" Negation: For all birds, if they have wings then they can fly")
print(" Contrapositive: Exist a bird, who can fly but have not wing")
print(" Coverse: Exist a bird, who can't fly but have wing")
print(" Inverse: Exist a bird, who have not wing but can fly")